# Generated by Django 3.0.3 on 2020-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200209_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='job',
            name='count_people',
            field=models.IntegerField(verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='job',
            name='find',
            field=models.IntegerField(verbose_name='Найдено людей'),
        ),
    ]
